# DataSet Example


We use a simple dataframe for demonstration

In [40]:
import pandas as pd

df = pd.read_csv("C:/Users/ZHou/Desktop/Python-Study-Notes/MachineLearning/MachingLearningFromStandford/My solution to Course Assignments/Linear Regression/ex1data1.txt",
                header=None, names=['Population', 'Profit'])

In [87]:
df.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [42]:
import numpy as np
x0 = pd.DataFrame({"x0": np.ones(df.shape[0])})
X = pd.concat([x0, df.iloc[:, 0]], axis = 1)
y = df.iloc[:, 1:]

# Algo1: Normal Equation

The best parameter can be directly calculated by
 $$ \Theta = (X^TX)^{-1}X^Ty$$

In [43]:
# Using normal equations
theta = np.linalg.inv(X.T@X)@X.T@y
theta

Profit
0 -3.895781
1  1.193034

Since it requires inverse, then its running time would be around $O(n^3)$

# Algo2: SVD (Singular Value Decomposation)

It is directly implemented with LinearRegressio in sklearn library

In [48]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()b
model.fit(df.iloc[:, 0:1], y)
model.intercept_, model.coef_

(array([-3.89578088]), array([[1.19303364]]))

The run time is around $O(n^2)$

# Algo3: Bath Gradient Descent

In [75]:
# batch gradiant descent compute manually
alpha = 0.01
iters = 1000

X1 = np.matrix(X)
y1 = np.matrix(y)

theta = np.matrix([[0,0]]).T
print(X.shape, y.shape, theta.shape)

def gradientDescent(X, y, theta, alpha, iters):
    for times in range(iters):
        gradient = 1/len(X) * X.T@(X@(theta) -y)
        theta = theta - alpha * gradient
    return theta

theta = gradientDescent(X1, y1, theta, alpha, iters)

theta

(97, 2) (97, 1) (2, 1)


matrix([[-3.24140214],
        [ 1.1272942 ]])

In [136]:
# batch gradient descent with sklearn algorithm
from sklearn.linear_model import SGDClassifier

classifier = SGDClassifier(max_iter=1000, tol=1e-3)
X = df.iloc[:, 0:1]
X = X.astype("int")
classifier.fit(np.array(X), np.array(y).ravel())
classifier.intercept_, classifier.coef_

(array([  48.42880597,   65.20520119,  144.10232167,  161.80982067,
          67.58373035,  126.8840641 ,   72.41468691,   68.32886844,
          19.94725224,  -30.22564221,  -52.38867292,  -22.09395053,
         -49.53613713,  -10.97644283,  -70.87609297,  -49.356075  ,
         -84.72629024,  -34.19356001, -179.85455247, -197.22202735,
         -58.70433527, -147.93874276, -229.75100502]),
 array([[-2.17959895e+01],
        [-1.84998318e+01],
        [-3.33333333e+01],
        [-4.26015337e+01],
        [-5.75221239e+01],
        [-2.81690141e+01],
        [-2.62329486e+01],
        [-2.81401893e+01],
        [-1.38696255e+01],
        [-7.28597450e+00],
        [-4.54416359e+01],
        [-1.52361605e+01],
        [ 1.45081422e-13],
        [-2.92056075e+01],
        [-2.30566535e+01],
        [ 2.92056075e+00],
        [-8.14995925e+00],
        [-3.20512821e+01],
        [-4.24268137e+00],
        [ 8.29187396e+00],
        [-6.32511069e+00],
        [ 2.55819903e+00],
        [-3

# ALgo4: Stochastic Gradient Descent

In [132]:
sgd_reg = SGDClassifier(max_iter = 1000, tol=1e-3, penalty=None, eta0=0.1)
X = df.iloc[:, 0:1]
X = X.astype("int")
sgd_reg.fit(X, y)

sgd_reg.coef_

C:\Users\ZHou\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[-12.02166102],
       [-17.9124805 ],
       [-35.98000755],
       [-42.56868355],
       [-36.46226262],
       [-24.94502154],
       [-22.91965839],
       [-34.49981575],
       [ -1.60631209],
       [-36.01769533],
       [  2.79466039],
       [-15.18716712],
       [ -8.7543568 ],
       [-60.44924186],
       [-52.23128571],
       [-17.29582867],
       [-10.24269288],
       [-49.74948162],
       [-62.69504847],
       [-17.39234205],
       [-28.00737145],
       [-17.45453384],
       [  1.27320682]])

In [128]:
index = range(0, len(X))
new_X = pd.concat([pd.Series(index), df.iloc[:, 0:1]], axis = 1)

new_X = np.array(new_X)

new_X = new_X.astype('int')
y = y.astype('int')
np.array(y).ravel().dtype

dtype('int32')